# Generated by Django 4.2.17 on 2025-02-14 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, default='password1234')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessLicense',
            fields=[
                ('TIN', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('given_date', models.DateField()),
                ('expired_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('training_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('t_type', models.CharField(blank=True, max_length=60)),
                ('start_date', models.DateField(null=True)),
                ('description', models.TextField(max_length=1000)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, default='password1234')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('age', models.PositiveIntegerField(default=18)),
                ('sex', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=10)),
                ('educationLevel', models.CharField(default='basic learning', max_length=30)),
                ('amharic', models.BooleanField(default=True)),
                ('afaan_oromo', models.BooleanField(default=False)),
                ('tigrigna', models.BooleanField(default=False)),
                ('sidamegna', models.BooleanField(default=False)),
                ('ownBussiness', models.BooleanField(default=False)),
                ('assigned_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.trainingtype')),
                ('business_tin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.businesslicense')),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('cont_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('agreement_date', models.DateField(auto_now_add=True)),
                ('lasting_date', models.DateField()),
                ('for_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainingtype')),
                ('sign_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Certifcate',
            fields=[
                ('cert_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('certi_doc', models.FileField(default='defualt.jpg', upload_to='images/')),
                ('awarded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainer')),
                ('cert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainingtype')),
            ],
        ),
    ]
