# Generated by Django 4.2.17 on 2025-02-14 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_alter_admin_id_alter_trainer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7e565a48-eab4-11ef-ab2d-0000000caf70'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7e565a48-eab4-11ef-ab2d-0000000caf70'), editable=False, primary_key=True, serialize=False),
        ),
    ]
